apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-client.fullname" . }}
  labels:
    {{- include "mongo-client.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "3000"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mongo-client.selectorLabels" . | nindent 4 }}
