{
 "title": "MongoDB client tests",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "driverWithVersion",
    "label": "drivers",
    "query": {
     "query": "label_values(mongodb_client_test_tasks_total, driverWithVersion)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver events by types / hour",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_driver_events_total{driverWithVersion=~\"$driverWithVersion\"}[1h])) by (eventName)",
       "legendFormat": "{{eventName}}"
      }
     ]
    },
    {
     "title": "Connection events by types / hour",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_connection_events_total{driverWithVersion=~\"$driverWithVersion\"}[1h])) by (eventName)",
       "legendFormat": "{{eventName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heart beats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heartbeats started / 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_driver_events_total{driverWithVersion=~\"$driverWithVersion\",eventName=\"serverHeartbeatStarted\"}[5m])) by (value)",
       "legendFormat": "{{value}}"
      }
     ]
    },
    {
     "title": "Heartbeats succeeded / 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_driver_events_total{driverWithVersion=~\"$driverWithVersion\", eventName=\"serverHeartbeatSucceeded\"}[5m])) by (value)",
       "legendFormat": "{{value}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topology changed / 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_driver_events_total{driverWithVersion=~\"$driverWithVersion\", eventName=\"serverDescriptionChanged\"}[5m]))",
       "legendFormat": "server description changed"
      },
      {
       "expr": "sum(increase(mongodb_client_test_driver_events_total{driverWithVersion=~\"$driverWithVersion\", eventName=\"topologyDescriptionChanged\"}[5m]))",
       "legendFormat": "topology changed"
      }
     ]
    },
    {
     "title": "Primary changed / 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_primary_change_total{driverWithVersion=~\"$driverWithVersion\"}[5m])) by (nodeName)",
       "legendFormat": "{{nodeName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection (nodejs only)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconnected / 5m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_connection_events_total{driverWithVersion=~\"$driverWithVersion\", eventName=\"reconnected\"}[5m])) by (driverWithVersion)",
       "legendFormat": "{{driverWithVersion}}"
      }
     ]
    },
    {
     "title": "Forced reconnect / 5m",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_connection_events_total{driverWithVersion=~\"$driverWithVersion\", eventName=\"forcedReconnection\"}[5m])) by (driverWithVersion)",
       "legendFormat": "{{driverWithVersion}}"
      }
     ]
    },
    {
     "title": "Disconnected duration / 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_reconnect_duration_sum{driverWithVersion=~\"$driverWithVersion\"}[5m])) by (driverWithVersion) / sum(increase(mongodb_client_test_reconnect_duration_count{driverWithVersion=~\"$driverWithVersion\"}[5m])) by (driverWithVersion)",
       "legendFormat": "{{driverWithVersion}}"
      }
     ]
    },
    {
     "title": "Disconnected duration per time bucket / 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"1\"}[5m])) - sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"0.1\"}[5m]))",
       "legendFormat": "0.1 to 1 sec"
      },
      {
       "expr": "sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"5\"}[5m])) - sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"1\"}[5m]))",
       "legendFormat": "1 to 5 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"10\"}[5m])) - sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"5\"}[5m]))",
       "legendFormat": "5 to 10 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"30\"}[5m])) - sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"10\"}[5m]))",
       "legendFormat": "10 to 30 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"60\"}[5m])) - sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"30\"}[5m]))",
       "legendFormat": "30 to 60 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"120\"}[5m])) - sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"60\"}[5m]))",
       "legendFormat": "60  to 120 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"+Inf\"}[5m])) - sum(increase(mongodb_client_test_reconnect_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"120\"}[5m]))",
       "legendFormat": "> 120 secs"
      }
     ]
    },
    {
     "title": "First time to complete a task after a disconnect, duration / 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_time_to_first_query_duration_sum{driverWithVersion=~\"$driverWithVersion\"}[5m])) by (driverWithVersion) / sum(increase(mongodb_client_test_time_to_first_query_duration_count{driverWithVersion=~\"$driverWithVersion\"}[5m])) by (driverWithVersion)",
       "legendFormat": "{{driverWithVersion}}"
      }
     ]
    },
    {
     "title": "First time to complete a task after a disconnect, per time bucket / 5m",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"1\"}[5m])) - sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"0.1\"}[5m]))",
       "legendFormat": "0.1 to 1 sec"
      },
      {
       "expr": "sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"5\"}[5m])) - sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"1\"}[5m]))",
       "legendFormat": "1 to 5 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"10\"}[5m])) - sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"5\"}[5m]))",
       "legendFormat": "5 to 10 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"30\"}[5m])) - sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"10\"}[5m]))",
       "legendFormat": "10 to 30 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"60\"}[5m])) - sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"30\"}[5m]))",
       "legendFormat": "30 to 60 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"120\"}[5m])) - sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"60\"}[5m]))",
       "legendFormat": "60  to 120 secs"
      },
      {
       "expr": "sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"+Inf\"}[5m])) - sum(increase(mongodb_client_test_time_to_first_query_duration_bucket{driverWithVersion=~\"$driverWithVersion\", le=\"120\"}[5m]))",
       "legendFormat": "> 120 secs"
      }
     ]
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Successful tasks / 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_client_test_tasks_total{driverWithVersion=~\"$driverWithVersion\", result=\"success\"}[5m])) by (driverWithVersion)",
     "legendFormat": "{{driverWithVersion}}"
    }
   ]
  },
  {
   "title": "Task duration / 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_client_test_task_duration_sum{driverWithVersion=~\"$driverWithVersion\"}[5m])) by (driverWithVersion) / sum(increase(mongodb_client_test_task_duration_count{driverWithVersion=~\"$driverWithVersion\"}[5m])) by (driverWithVersion)",
     "legendFormat": "{{driverWithVersion}}"
    }
   ]
  },
  {
   "title": "Failed tasks / 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_client_test_tasks_total{driverWithVersion=~\"$driverWithVersion\", result=\"failure\"}[5m])) by (driverWithVersion)",
     "legendFormat": "{{driverWithVersion}}"
    }
   ]
  },
  {
   "title": "Number of tasks per time bucket / 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"1([.]0)?\"}[5m])) - sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=\"0.1\"}[5m]))",
     "legendFormat": "0.1 to 1 sec"
    },
    {
     "expr": "sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"5([.]0)?\"}[5m])) - sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"1([.]0)?\"}[5m]))",
     "legendFormat": "1 to 5 secs"
    },
    {
     "expr": "sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"10([.]0)?\"}[5m])) - sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"5([.]0)?\"}[5m]))",
     "legendFormat": "5 to 10 secs"
    },
    {
     "expr": "sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"30([.]0)?\"}[5m])) - sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"10([.]0)?\"}[5m]))",
     "legendFormat": "10 to 30 secs"
    },
    {
     "expr": "sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"60([.]0)?\"}[5m])) - sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"30([.]0)?\"}[5m]))",
     "legendFormat": "30 to 60 secs"
    },
    {
     "expr": "sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"120([.]0)?\"}[5m])) - sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"60([.]0)?\"}[5m]))",
     "legendFormat": "60  to 120 secs"
    },
    {
     "expr": "sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=\"+Inf\"}[5m])) - sum(increase(mongodb_client_test_task_duration_bucket{driverWithVersion=~\"$driverWithVersion\",le=~\"120([.]0)?\"}[5m]))",
     "legendFormat": "> 120 secs"
    }
   ]
  },
  {
   "title": "Skipped tasks / 5m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_client_test_skipped_tasks_total{driverWithVersion=~\"$driverWithVersion\"}[5m])) by (driverWithVersion)",
     "legendFormat": "{{driverWithVersion}}"
    }
   ]
  },
  {
   "title": "Compute",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{pod=~\"mongo-client-.*\", container=\"mongo-client\"}[5m])*100) by (pod)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_memory_usage_bytes{pod=~\"mongo-client-.*\", container=\"mongo-client\"}[5m])*100) by (pod)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Pod restarts / hour",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"mongo-client-.*\"}[1h]))",
       "legendFormat": "mongo-test"
      }
     ]
    }
   ]
  }
 ]
}